#!/bin/bash -e

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
. "$SCRIPT_DIR/util.sh"

BASE="http://localhost:8080"
CURL_RESPONSE=$(curl -s "$BASE/query/execute-cohort" -H "Content-Type: application/sq+json" -d @"$SCRIPT_DIR/../integration-test/query-$1.json")

ACTUAL_PAT_ID_ARRAY=()

while IFS= read -r line; do
    ACTUAL_PAT_ID_ARRAY+=("$line")
done < <(echo "$CURL_RESPONSE" | jq -r '.[]')

EXPECTED_PAT_ID_ARRAY=(
                          "DEZLXBBZCMJRHIWP" "DEZLXBBZGCL4O6LJ" "DEZLXBC7JY7I7VTM" "DEZLXBCWHPIDEXQP"
                          "DEZLXBD2ZFD7ICE5" "DEZLXBD6YMHCAI5B" "DEZLXBDDTY5KODRB" "DEZLXBDGKPNNPOLS"
                          "DEZLXBDLW2IYJNEV" "DEZLXBDQSTBEEKD3" "DEZLXBDVCCO6KA5K" "DEZLXBDYX5VLFMDF"
                          "DEZLXBEGC5T2PBAM" "DEZLXBEJDWUZP7A5" "DEZLXBEKK3HVHOCL" "DEZLXBESEJYLN2RV"
                          "DEZLXBEZ5C5V77WP" "DEZLXBF4MNTUBRUT" "DEZLXBFBLJUS3IS6" "DEZLXBFE2ON4CWLO"
                          "DEZLXBG3MKK6PUVX" "DEZLXBG7NVKBU3JG" "DEZLXBGKPFVZ7AI3" "DEZLXBGKU74A44Z7"
                          "DEZLXBGQ44BQHYDL" "DEZLXBGQDKOZHFU6" "DEZLXBGTXJS2VHEG" "DEZLXBGVQRWEBUGV"
                          "DEZLXBH6JTYKLN37" "DEZLXBHP4DGCTTRN" "DEZLXBHQG2CBAKXS" "DEZLXBI4I24ZCM3H"
                          "DEZLXBI5A2TSPB5S" "DEZLXBIIP6ZUTPIA" "DEZLXBIMZPVN64B3" "DEZLXBIT7CK3VRVH"
                          "DEZLXBIUGA4R4KTC" "DEZLXBJJWNJTPMYC" "DEZLXBK3LRLPGP2U" "DEZLXBK4R55CSR2X"
                          "DEZLXBKAF4GKMAQD" "DEZLXBKFWGK4TDK5" "DEZLXBKIQNZAHQJV" "DEZLXBL7YHECLK7W"
                          "DEZLXBLD72E7CEJT" "DEZLXBLFX7YBP6HI" "DEZLXBLNYKQLJS5T" "DEZLXBLQGE5EKJGE"
                          "DEZLXBM7F2I6MGPG" "DEZLXBMJLDY5OXHS" "DEZLXBMOJAE635MI" "DEZLXBMQR4FTZKEP"
                          "DEZLXBN5O5IJB2OM" "DEZLXBN7PFFZDAYM" "DEZLXBNCGIA6Y2P7" "DEZLXBNIU42GXBTO"
                          "DEZLXBNM37HOP6GW" "DEZLXBNU37U7ZIFR" "DEZLXBNY4SPRN7MD" "DEZLXBOS3OMTQZ42"
                          "DEZLXBPJTYSY4PUU" "DEZLXBPJZEVQ6JYY" "DEZLXBPNIOO7JG4O" "DEZLXBPSXO5T4ZIO"
                          "DEZLXBQI5WPVLRR4" "DEZLXBQWR5KHBB44" "DEZLXBR4IC6RUSTD" "DEZLXBRJ4TA7BJYV"
                          "DEZLXBS5QKVCQCTT"
                      )

test_array "cohort test" ACTUAL_PAT_ID_ARRAY EXPECTED_PAT_ID_ARRAY
