flare:
  cohort:
    enabled: ${FLARE_ENABLE_COHORT_ENDPOINT:false}
  fhir:
    server: 'http://localhost:8082/fhir'
    user: ''
    password: ''
    maxConnections: ${FLARE_FHIR_MAX_CONNECTIONS:4}
    maxQueueSize: ${FLARE_FHIR_MAX_QUEUE_SIZE:500}
    pageCount: ${FLARE_FHIR_PAGE_COUNT:1000}
  cache:
    mem:
      sizeMB: ${FLARE_CACHE_MEM_SIZE_MB:1024}
      expire: 'PT48H'
      refresh: 'PT24H'
    disk:
      path: 'cache'
      expire: 'P7D'
      threads: 4

server:
  port: 8080

logging:
  level:
    com:
      github:
        benmanes:
          caffeine: 'error'
    de:
      medizininformatikinitiative:
        flare: ${LOG_LEVEL:info}
