services:
  data-store:
    image: "samply/blaze:0.29"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8080/health"]
      interval: "5s"
      timeout: "5s"
      retries: "3"
      start_period: "60s"
    environment:
      BASE_URL: "http://data-store:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      LOG_LEVEL: "debug"
    ports:
      - "8082:8080"
    volumes:
      - "data-store-data:/app/data"
  flare:
    image: "flare:latest"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8080/cache/stats"]
      interval: "5s"
      timeout: "5s"
      retries: "3"
      start_period: "60s"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      FLARE_FHIR_SERVER: "http://proxy:8080/fhir"
      FLARE_FHIR_USER: "test"
      FLARE_FHIR_PASSWORD: "bar"
      LOG_LEVEL: "debug"
    ports:
      - "8080:8080"
    volumes:
      - "flare-cache:/app/cache"
      - "../synthea-test-mapping:/app/ontology"
    depends_on:
      - data-store
  proxy:
    image: "nginx:1.27.1"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy.htpasswd:/etc/auth/.htpasswd"

volumes:
  data-store-data:
  flare-cache:
